export const FILTER_COMPLETED = 'filter_completed'
export const FILTER_AZ = 'filter_az'
export const FILTER_ZA = 'filter_za'
export const FILTER_TIME = 'filter_time'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'